# CODE APRIL
Created_by: Promise Ekeh

Date: April 2024

Week 2 ( Day 8- day 14)

In [1]:
import pandas as pd

# Day 8:

Python dictionary methods


## 1. What is a dictionary in Python? How is it different from a list?
A dictionary in Python is a collection of key-value pairs. Each key is unique, and it maps to a value. 

Dictionaries are mutable, meaning they can be changed after creation, and they are unordered, meaning the items do not have a specific order


**Key Features of a Dictionary:**

Key-Value Pairs: Each item in a dictionary is a pair of keys and values.
Unique Keys: Keys in a dictionary must be unique and immutable (e.g., strings, numbers, tuples).
Mutable: Dictionaries can be modified by adding, updating, or removing key-value pairs.
Unordered: Dictionaries do not maintain any order for the elements.

**Differences Between a Dictionary and a List:**

Structure: Lists are ordered collections of elements indexed by positions (integers starting from 0), whereas dictionaries are unordered collections of key-value pairs.
Access: List elements are accessed by their index, while dictionary elements are accessed by their keys.

## 2. Write a Python code snippet to demonstrate at least two dictionary methods.


## 3. Create a dictionary inventory representing the count of first ten (10)  items in a store: 

eg ('apple': 10 'banana': 15,  'orange': 8). 


In [1]:
inventory = {
    'apple': 10,
    'banana': 15,
    'orange': 8,
    'grape': 12,
    'mango': 5,
    'pear': 7,
    'peach': 9,
    'plum': 4,
    'kiwi': 3,
    'pineapple': 6
}
inventory

{'apple': 10,
 'banana': 15,
 'orange': 8,
 'grape': 12,
 'mango': 5,
 'pear': 7,
 'peach': 9,
 'plum': 4,
 'kiwi': 3,
 'pineapple': 6}

In [2]:

# Removing the 7th item (peach)
inventory.pop('peach')


9

In [3]:
inventory

{'apple': 10,
 'banana': 15,
 'orange': 8,
 'grape': 12,
 'mango': 5,
 'pear': 7,
 'plum': 4,
 'kiwi': 3,
 'pineapple': 6}

In [4]:

# Calculating the total count of items in the dictionary

inventory.keys()


dict_keys(['apple', 'banana', 'orange', 'grape', 'mango', 'pear', 'plum', 'kiwi', 'pineapple'])

In [5]:
inventory.values()

dict_values([10, 15, 8, 12, 5, 7, 4, 3, 6])

In [6]:
sum(inventory.values())

70

In [7]:
# Add 5 more of the first items,
inventory['apple'] += 5
inventory

{'apple': 15,
 'banana': 15,
 'orange': 8,
 'grape': 12,
 'mango': 5,
 'pear': 7,
 'plum': 4,
 'kiwi': 3,
 'pineapple': 6}

In [8]:
#  3 more of the 6th item 
inventory['pear'] += 3
inventory

{'apple': 15,
 'banana': 15,
 'orange': 8,
 'grape': 12,
 'mango': 5,
 'pear': 10,
 'plum': 4,
 'kiwi': 3,
 'pineapple': 6}

In [9]:
# and remove the 7th item from the dictionary. 
inventory.pop('kiwi')



3

In [10]:
inventory

{'apple': 15,
 'banana': 15,
 'orange': 8,
 'grape': 12,
 'mango': 5,
 'pear': 10,
 'plum': 4,
 'pineapple': 6}

In [11]:
# Print the total count of items in the dictionary.
total_count = sum(inventory.values())
print(f"Total count of items in the inventory: {total_count}")

Total count of items in the inventory: 75


# Day 9:

Python tuple & set methods


## 1. What is a tuple & set  in Python? How are they different from a list?


A tuple is an immutable, ordered collection of elements in Python. Once a tuple is created, its elements cannot be modified. Tuples are defined using parentheses ().

**Key Features:**

* Immutable: Once created, the elements of a tuple cannot be changed.
* Ordered: The elements in a tuple have a defined order.
* Heterogeneous: A tuple can contain elements of different data types.


A set is an unordered collection of unique elements in Python. Sets are defined using curly braces {} or the set() function.

**Key Features:**
* Unique Elements: Duplicate elements are not allowed in a set.
* Unordered: The elements in a set do not have a defined order.
* Mutable: Elements can be added or removed from a set.



**Differences Between Tuples, Sets, and Lists:**

__Mutability:__
* Lists are mutable (elements can be changed).
* Tuples are immutable (elements cannot be changed).
* Sets are mutable but do not allow duplicate elements.

__Order:__

* Lists and tuples are ordered (elements have a defined order).
* Sets are unordered (elements do not have a defined order).

__Syntax:__

*  Lists use square brackets [].
*  Tuples use parentheses ().
*  Sets use curly braces {}.

## 2. Create a tuple my_tuple containing a sequence of 15 integers.


In [13]:
my_tuple = (12, 2, 3, 8, 5, 6, 7, 8, 12, 10, 8, 12, 6, 14, 3)
my_tuple

(12, 2, 3, 8, 5, 6, 7, 8, 12, 10, 8, 12, 6, 14, 3)

### 2a Print the original tuple, 


In [14]:
print(my_tuple)

(12, 2, 3, 8, 5, 6, 7, 8, 12, 10, 8, 12, 6, 14, 3)


### 2b Use the count() method to count the number of occurrences of a specified integer in the tuple.


In [15]:
count_12 = my_tuple.count(12)
print("Number of occurrences of 12 in the tuple:", count_12)

Number of occurrences of 12 in the tuple: 3


### 2c Use tuple concatenation (+) to create a new tuple by combining my_tuple with another tuple of your choice.


In [16]:
another_tuple = (16, 17, 18)
new_tuple = my_tuple + another_tuple

### 2d Print the modified tuple after concatenation.


In [17]:
print("Modified tuple after concatenation:", new_tuple)

Modified tuple after concatenation: (12, 2, 3, 8, 5, 6, 7, 8, 12, 10, 8, 12, 6, 14, 3, 16, 17, 18)


## 3. Create two sets set1 and set2 containing integers or strings.


In [18]:
set1 = {1, 2, 3, 4, 5}
set2 = {4, 5, 6, 7, 8}

### 3a Print the union of set1 and set2 using the | operator.


In [19]:
union_set = set1 | set2
print("Union of set1 and set2:", union_set)

Union of set1 and set2: {1, 2, 3, 4, 5, 6, 7, 8}


### 3b Print the intersection of set1 and set2 using the & operator.


In [20]:
intersection_set = set1 & set2
print("Intersection of set1 and set2:", intersection_set)

Intersection of set1 and set2: {4, 5}


### 3c Print the difference between set1 and set2 using the - operator.


In [21]:
difference_set = set1 - set2
print("Difference between set1 and set2:", difference_set)

Difference between set1 and set2: {1, 2, 3}


In [14]:
difference_set2 = set2 - set1
print("Difference between set1 and set2:", difference_set2)

Difference between set1 and set2: {8, 6, 7}


### 3d Add new elements to set1 using the add() method and remove specific elements using the remove() method.


In [15]:
set1.add(9)
set1.add(10)
print("set1 after adding new elements:", set1)

set1 after adding new elements: {1, 2, 3, 4, 5, 9, 10}


In [16]:
set1.remove(1)
print("set1 after removing an element:", set1)

set1 after removing an element: {2, 3, 4, 5, 9, 10}


# Day 10

Advanced control flow (list comprehensions, lambda functions)


## 1. Explain what list comprehensions are in Python. Provide an example


List comprehensions provide a concise way to create lists in Python. They consist of brackets containing an expression followed by a for clause, and can also include if clauses. List comprehensions are more compact and faster than traditional for loops for creating lists.

[expression for item in iterable if condition]


## 2. What are lambda functions (anonymous functions) in Python? 

Lambda functions, also known as anonymous functions, are small, unnamed functions defined using the lambda keyword. They can have any number of arguments but only one expression. Lambda functions are often used for short, throwaway functions.

lambda arguments: expression

__Give an example of using lambda functions__


In [17]:
# Using a lambda function to create a function that squares a number
square = lambda x: x**2
print(square(5))  # Output: 25


25


## 3. Write Python expressions using list comprehensions to achieve the following:
### 3a Create a list containing the squares of numbers from 1 to 10


In [18]:
# Creating a list of squares of numbers from 1 to 10 using list comprehension
squares = [x**2 for x in range(1, 11)]
print(squares)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


### 3b Create a list containing even numbers less than 20 


In [19]:
even_numbers = [x for x in range(20) if x % 2 == 0]
print(even_numbers) 

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


## 4. Create a list of ten animals and return a list of animals with more that 4 letter


In [22]:
animals = ['cat', 'dog', 'elephant', 'giraffe', 'lion', 'tiger', 'bear', 'rabbit', 'fox', 'zebra']

# Using list comprehension to get animals with more than 4 letters
long_named_animals = [an for an in animals if len(an) > 4]
print(long_named_animals)

['elephant', 'giraffe', 'tiger', 'rabbit', 'zebra']


## 5. Create a list temperatures_celsius containing 10 numbers, 

using list comprehension

In [24]:
temperatures_celsius = [-10, -25, 15, 20, 25, 30, 35, 40, 45, 50]

### 5a  convert each temperature in Fahrenheit & store in temperatures_fahrenheit

---
$celcius  *  9 /5 + 32 $ 


In [25]:
temperatures_fahrenheit = [(temp * 9/5) + 32 for temp in temperatures_celsius]
print(temperatures_fahrenheit) 

[14.0, -13.0, 59.0, 68.0, 77.0, 86.0, 95.0, 104.0, 113.0, 122.0]


### 5b Store the temperatures that are greater than or equal to 28 degrees Fahrenheit a new list called warm_temperatures


In [26]:
# using list comprehension
warm_temperatures = [temp for temp in temperatures_fahrenheit if temp >= 28]
print(warm_temperatures) 

[59.0, 68.0, 77.0, 86.0, 95.0, 104.0, 113.0, 122.0]


In [27]:
# using lambda
warm_temperatures = list(filter(lambda temp: temp >= 28, temperatures_fahrenheit))

### 5c Using lambda function square all the items in temperatures_fahrenheit 

In [28]:
squared_temperatures = list(map(lambda x: x**2, temperatures_fahrenheit))
print(squared_temperatures) 

[196.0, 169.0, 3481.0, 4624.0, 5929.0, 7396.0, 9025.0, 10816.0, 12769.0, 14884.0]


In [29]:
[temp**2 for temp in temperatures_fahrenheit]

[196.0,
 169.0,
 3481.0,
 4624.0,
 5929.0,
 7396.0,
 9025.0,
 10816.0,
 12769.0,
 14884.0]

# Day 11:

Introduction to NumPy library for numerical computing


## 1. What is NumPy? Why is it widely used in data analysis?

NumPy (Numerical Python) is a fundamental and powerful library in Python used for numerical computations and working with large, multi-dimensional arrays and matrices. It provides efficient implementations of mathematical functions that operate on arrays. making it a fundamental library for scientific computing in Python


Performance: NumPy arrays are more efficient than Python lists for numerical computations because they are implemented in C, allowing for faster processing.

Functionality: NumPy offers a comprehensive library of mathematical functions, including linear algebra, statistical operations, and Fourier transforms.

Convenience: NumPy arrays provide more convenient and readable syntax for array operations, especially for complex operations involving multi-dimensional arrays.


## 2. Describe three advantages of using NumPy arrays over Python lists for numerical computing


**Speed:** NumPy arrays are optimized for performance with vectorized operations that are significantly faster than traditional Python loops. This results in faster execution times for large-scale numerical computations.

Memory Efficiency: NumPy arrays use less memory compared to Python lists. They store elements of the same type in contiguous memory locations, reducing overhead and improving cache performance.
Advanced Mathematical Functions: NumPy provides a wide range of powerful mathematical functions that are not available with Python lists. These functions are optimized for performance and can be applied directly to arrays, making numerical computations more straightforward and efficient.

## 3. Write a Python code to import NumPy and print its version.


In [30]:
import numpy as np

# Printing the version of NumPy
print("NumPy version:", np.__version__)


NumPy version: 1.26.4


## 4. Create a list of 12 integers, using NumPy do the following:


In [31]:

python_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

### 4a Create a NumPy array from the Python list


In [32]:
numpy_array = np.array(python_list)
print("1D NumPy array:", numpy_array)

1D NumPy array: [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [33]:
type(numpy_array)

numpy.ndarray

In [35]:
numpy_array.ndim

1

In [30]:
print("Type 1D NumPy array:", type(numpy_array))

Type 1D NumPy array: <class 'numpy.ndarray'>


### 4b Create a 2D NumPy array (matrix) from a nested Python list


In [36]:
nested_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]
nested_list

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]

In [37]:

# Creating a 2D NumPy array from the nested Python list
numpy_2d_array = np.array(nested_list)
# print("2D NumPy array:\n", numpy_2d_array)
numpy_2d_array

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [38]:
numpy_2d_array.ndim

2

### 4c Reshape the  1D to 3D


In [39]:
numpy_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [40]:
numpy_array.reshape((2, 3, 2))

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [32]:
numpy_3d_array = numpy_array.reshape((2, 3, 2))
print("3D NumPy array:\n", numpy_3d_array)

3D NumPy array:
 [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


## 5. Create a 3D NumPy array (matrix) from a nested Python list


In [41]:
nested_3d_list = [
    [[1, 2], [3, 4], [5, 6]],
    [[7, 8], [9, 10], [11, 12]]
]

# Creating a 3D NumPy array from the nested Python list
numpy_3d_array_from_list = np.array(nested_3d_list)
print("3D NumPy array from nested list:\n", numpy_3d_array_from_list)


3D NumPy array from nested list:
 [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [42]:
numpy_3d_array_from_list.shape

(2, 3, 2)

In [43]:
numpy_3d_array_from_list.ndim

3

## 6. Create a NumPy array of zeros and ones


In [44]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [34]:
zeros_array = np.zeros((3, 4))  # 3x4 matrix of zeros
print("NumPy array of zeros:\n", zeros_array)

NumPy array of zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [45]:
ones_array = np.ones((2, 5))  # 2x5 matrix of ones
print("NumPy array of ones:\n", ones_array)

NumPy array of ones:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


# Day 12:

NumPy arrays and indexing


## 1. What’s the difference between copy and view?

Copy: When you create a copy of a NumPy array, a new array is created, and the original array is not affected by changes made to the copy. This is done using the copy() method.
View: When you create a view of a NumPy array, it is essentially a new array object that looks at the same data as the original array. Changes made to the view will affect the original array and vice versa.

In [46]:
original = np.array([1, 2, 3, 4, 5])
original

array([1, 2, 3, 4, 5])

In [47]:
# Creating a copy
copy_array = original.copy()
copy_array[0] = 10
print("Original array after modifying copy:", original)
print("Copy array:", copy_array)

Original array after modifying copy: [1 2 3 4 5]
Copy array: [10  2  3  4  5]


In [48]:
view_array = original.view()
view_array[0] = 10
print("Original array after modifying view:", original)
print("View array:", view_array) 

Original array after modifying view: [10  2  3  4  5]
View array: [10  2  3  4  5]


## 2. What’s the difference between np.concatenate & np.stack

np.concatenate: Joins a sequence of arrays along an existing axis. You can specify the axis along which to concatenate using the axis parameter.

np.stack: Joins a sequence of arrays along a new axis. This effectively increases the number of dimensions of the resulting array.


In [50]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])


In [40]:

# Concatenate along the first axis (rows)
concat_array = np.concatenate((arr1, arr2), axis=0)
print("Concatenate along rows:\n", concat_array)


Concatenate along rows:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [41]:
# Stack along a new axis
stack_array = np.stack((arr1, arr2), axis=0)
print("Stack along a new axis:\n", stack_array)

Stack along a new axis:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [53]:
arr1

array([[1, 2],
       [3, 4]])

In [54]:
arr2

array([[5, 6],
       [7, 8]])

In [51]:
np.stack((arr1, arr2), axis=0)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [52]:
np.stack((arr1, arr2), axis=1)

array([[[1, 2],
        [5, 6]],

       [[3, 4],
        [7, 8]]])

## 3. Create an array of shape (3, 4),
 using indexing:


In [55]:
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### 3a Get the 3rd item in the 2nd row


In [56]:
item_3_2 = array[1, 2]
print("3rd item in the 2nd row:", item_3_2) 

3rd item in the 2nd row: 7


### 3b Get last item in the 1st row


In [44]:
last_item_1 = array[0, -1]
print("Last item in the 1st row:", last_item_1)

Last item in the 1st row: 4


In [57]:
array[0, 3]

4

### 3c Get last item in  the last row


In [45]:
last_item_last = array[-1, -1]
print("Last item in the last row:", last_item_last)

Last item in the last row: 12


### 3d Get 1st item in the first row


In [46]:
first_item_1 = array[0, 0]
print("1st item in the 1st row:", first_item_1)

1st item in the 1st row: 1


### 3e Get 1st item in the 2nd row


In [58]:
first_item_2 = array[1, 0]
print("1st item in the 2nd row:", first_item_2)

1st item in the 2nd row: 5


### 3f Get last 2 columns of the 1st 2 rows


In [48]:
last_2_cols = array[:2, -2:]
print("Last 2 columns of the 1st 2 rows:\n", last_2_cols)

Last 2 columns of the 1st 2 rows:
 [[3 4]
 [7 8]]


### 3g Get the second row of the array


In [49]:
second_row = array[1, :]
print("Second row of the array:", second_row)

Second row of the array: [5 6 7 8]


### 3h Get the last column of the array


In [50]:
last_column = array[:, -1]
print("Last column of the array:", last_column)

Last column of the array: [ 4  8 12]


### 3i Set the element in the 1st row, 3rd column to 10


In [51]:
array[0, 2] = 10
print("Array after setting element in 1st row, 3rd column to 10:\n", array)

Array after setting element in 1st row, 3rd column to 10:
 [[ 1  2 10  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## 4.  Create two NumPy arrays 3 by 3 arrays (arr1 & arr2)


In [52]:
arr1 = np.array([[1, 2, 3], 
                 [4, 5, 6], 
                 [7, 8, 9]])

arr2 = np.array([[10, 11, 12], 
                 [13, 14, 15], 
                 [16, 17, 18]])

### 4a Concatenate arrays vertically (along rows)


In [53]:
vertical_concat = np.concatenate((arr1, arr2), axis=0)
print("Concatenate vertically:\n", vertical_concat)

Concatenate vertically:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


### 4b Concatenate arrays horizontally (along columns)


In [54]:
horizontal_concat = np.concatenate((arr1, arr2), axis=1)
print("Concatenate horizontally:\n", horizontal_concat)

Concatenate horizontally:
 [[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


## 5. Create a 1 dimensional array of 10 integers:


In [60]:
one_d_array = np.array([10, 15, 22, 33, 40, 55, 60, 75, 80, 95])

### 5a Filter even numbers from the array


In [61]:
even_numbers = one_d_array[one_d_array % 2 == 0]
print("Even numbers:", even_numbers)

Even numbers: [10 22 40 60 80]


### 5b Check if value 5 exists in the array


In [57]:
contains_five = 5 in one_d_array
print("Contains 5:", contains_five)

Contains 5: False


In [63]:
60 in one_d_array

True

### 5c Sort the array in ascending order


In [58]:
sorted_array_asc = np.sort(one_d_array)
print("Sorted array in ascending order:", sorted_array_asc)

Sorted array in ascending order: [10 15 22 33 40 55 60 75 80 95]


### 5d Sort the array in descending order


In [59]:
sorted_array_desc = np.sort(one_d_array)[::-1]
print("Sorted array in descending order:", sorted_array_desc)

Sorted array in descending order: [95 80 75 60 55 40 33 22 15 10]


# Day 13:
Focus:
NumPy array operations, manipulation, aggregation and statistical functions


## 1. Highlight some common mathematical operations that can be performed on NumPy arrays.


Element-wise Operations: Addition, subtraction, multiplication, and division of arrays.

Aggregation Functions: Sum, mean, median, minimum, maximum, standard deviation, variance.

Linear Algebra: Matrix multiplication, dot product, eigenvalues, eigenvectors.

Trigonometric Functions: Sine, cosine, tangent, inverse sine, inverse cosine, inverse tangent.

Exponential and Logarithmic Functions: Exponential, natural logarithm, base 10 logarithm

## 2. Difference between Python aggregate functions and NumPy aggregate functions

Python aggregate functions, such as sum(), min(), max(), len(), are built-in functions that operate on iterables like lists, tuples, or sets, and return a single result.

NumPy aggregate functions, such as np.sum(), np.min(), np.max(), np.mean(), np.median(), np.std(), np.var(), are specifically designed to operate on NumPy arrays. They offer optimized performance for numerical computations and can handle multi-dimensional arrays efficiently.

## 3 Create a NumPy  3 by 3 array  and perform statistical operations


In [66]:
array = np.array([[1, 2, 3],
                  [7, 8, 9],
                  [3, 6, 1]
                  ])

### 3a Masking: Replace values greater than 5 with 0


In [61]:
masked_array = np.where(array > 5, 0, array)
masked_array

array([[1, 2, 3],
       [0, 0, 0],
       [3, 0, 1]])

### 3b Sorting: Sort rows based on the second column


In [67]:
array

array([[1, 2, 3],
       [7, 8, 9],
       [3, 6, 1]])

In [68]:
sorted_array = array[array[:, 1].argsort()]
sorted_array

array([[1, 2, 3],
       [3, 6, 1],
       [7, 8, 9]])

### 3c Unique Values: Extract unique elements and their counts


In [71]:
np.unique(array, return_counts=True)

(array([1, 2, 3, 6, 7, 8, 9]), array([2, 1, 2, 1, 1, 1, 1], dtype=int64))

In [69]:
unique_values, counts = np.unique(array, return_counts=True)

In [70]:
dict(zip(unique_values, counts))

{1: 2, 2: 1, 3: 2, 6: 1, 7: 1, 8: 1, 9: 1}

### 3d Get the range, min and max values


In [72]:
array_range = np.ptp(array)
array_min = np.min(array)
array_max = np.max(array)

print("Range:", array_range)
print("Min Value:", array_min)
print("Max Value:", array_max)

Range: 8
Min Value: 1
Max Value: 9


## 4. Create a random NumPy 4 by 6 array of int between 1 and 100 using a specific seed


In [79]:
# Set a specific seed for reproducibility
np.random.seed(0)

# Create a 4x6 NumPy array of integers between 1 and 100
random_array = np.random.randint(1, 101, size=(4, 6))
random_array

array([[45, 48, 65, 68, 68, 10],
       [84, 22, 37, 88, 71, 89],
       [89, 13, 59, 66, 40, 88],
       [47, 89, 82, 38, 26, 78]])

### 4a Sorting: Sort each row in descending order


In [80]:
sorted_descending = np.sort(random_array, axis=1)[:, ::-1]
sorted_descending

array([[68, 68, 65, 48, 45, 10],
       [89, 88, 84, 71, 37, 22],
       [89, 88, 66, 59, 40, 13],
       [89, 82, 78, 47, 38, 26]])

### 4b Aggregation: Compute sum, mean, min, and max along different axes


In [81]:
random_array

array([[45, 48, 65, 68, 68, 10],
       [84, 22, 37, 88, 71, 89],
       [89, 13, 59, 66, 40, 88],
       [47, 89, 82, 38, 26, 78]])

In [82]:
sum_axis0 = np.sum(random_array, axis=0)
sum_axis1 = np.sum(random_array, axis=1)
mean_axis0 = np.mean(random_array, axis=0)
mean_axis1 = np.mean(random_array, axis=1)
min_axis0 = np.min(random_array, axis=0)
min_axis1 = np.min(random_array, axis=1)
max_axis0 = np.max(random_array, axis=0)
max_axis1 = np.max(random_array, axis=1)

In [84]:
print("Sum along axis 0:", sum_axis0)
print("Sum along axis 1:", sum_axis1)
print("Mean along axis 0:", mean_axis0)
print("Mean along axis 1:", mean_axis1)
print("Min along axis 0:", min_axis0)
print("Min along axis 1:", min_axis1)
print("Max along axis 0:", max_axis0)
print("Max along axis 1:", max_axis1)

Sum along axis 0: [265 172 243 260 205 265]
Sum along axis 1: [304 391 355 360]
Mean along axis 0: [66.25 43.   60.75 65.   51.25 66.25]
Mean along axis 1: [50.66666667 65.16666667 59.16666667 60.        ]
Min along axis 0: [45 13 37 38 26 10]
Min along axis 1: [10 22 13 26]
Max along axis 0: [89 89 82 88 71 89]
Max along axis 1: [68 89 89 89]


### 4c Statistical Analysis: Compute median and percentile


In [70]:
median = np.median(random_array)
percentile_25 = np.percentile(random_array, 25)
percentile_75 = np.percentile(random_array, 75)

In [71]:
print("Median:", median)
print("25th Percentile:", percentile_25)
print("75th Percentile:", percentile_75)


Median: 65.5
25th Percentile: 39.5
75th Percentile: 82.5


### 4d Statistical Functions: Compute standard deviation and variance


In [72]:
std_deviation = np.std(random_array)
variance = np.var(random_array)

In [73]:
print("Standard Deviation:", std_deviation)
print("Variance:", variance)

Standard Deviation: 25.007082330145327
Variance: 625.3541666666666


## 5 Create an array of 10 fruits, randomly select 4 fruits from the array


In [89]:
fruits = np.array(['apple', 'banana', 'orange', 'grape', 'mango', 'pear', 'pineapple', 'kiwi', 'watermelon', 'strawberry'])

# Randomly select 4 fruits from the array
selected_fruits = np.random.choice(fruits, size=4, replace=False)

# Print the selected fruits
print("Selected Fruits:", selected_fruits)

Selected Fruits: ['apple' 'strawberry' 'orange' 'grape']


# Day 14
Rest Day

![alt text](../Images/Day%2014.png)